### ISSUE TITLE
 How to access my Device from anywhere using different Internet Service Provider(ISP)

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#123]
ESP8266 can connect to a websocket server using SSID and Password through a router and under that router can control the device but if try to use different ISP or router it is impossible to access the device using its IP. How can solve this big problem of IoT.

**Comment by cagdasdoner** [comment]
Basicly migrate your server to cloud. Get a domain name and bind it to your cloud ip address. Do all websock request to this domain name.

**Comment by williamesp2015** [comment]
@cagdasdoner 
I appreciate your help. Unfortunately I do't know any free cloud for testing my project and I couldn't understand how I can send data to my websocket running on my ESP8266 with an IP like 192.168.1.159 from anywhere around the glob.

**Comment by cagdasdoner** [comment]
So, i can suggest you to have a free tier account from amazon web services. It is free for one year. 
You'll get an instance of ubuntu (i am not sure about windows) and you can run your server on it. 

You can google "amazon ec2" for more info.

Once you have successfully launched to your instance, you gonna have an ip address attached on your instance that you can reach  from everywhere you want. 

You can use this address to create a web server connection while your websocket server is running on your instance.

Just type the ip address of your instance instead of 192.168.x.x.

This all stuff is a good way to get rid of hardness of accessing device behind the NAT. To resolve this, you can have a cloud based server as i mentioned or apply a port forwarding from your modem, which you should not prefer.

**Comment by williamesp2015** [comment]
@cagdasdoner,

Very interesting!!!. Unfortunately getting Amazon EC2 and other free cloud accounts, required Credit Card information that I don't want to do that. Is there a hassle free Cloud web hosting or ordinary web hosting way to solve this problem?
Thank you

**Comment by williamesp2015** [comment]
@cagdasdoner
Hi, now I have launched  Amazon EC2 and I have Instance ID, Instance Type, Availability Zone,Instance State,  Public DNS, Public IP. It is very different with web hosting regarding uploading the files and I don't know how to set my ESP8266 to connect to my Websocket Server from anywhere and view data from anywhere. 
Your help would be very appreciated.

**Comment by quantumlicht** [comment]
@williamesp2015, If you don't have any ability in networking or managing a linux box, I suggest you use heroku instead to deploy your websocket server.

Personnally, I use a node.js implementation of a websocket server (https://github.com/websockets/ws)

Heroku has some build-packs so the amount of setup to get things running is minimal.

**Comment by msahli2** [comment]
Hi  williamesp2015 
I think the solution may be easier  by using  wifimanager library to get to other accessible  ISP (of course use SSID & Password)
and you do not have to change any thing in your code !

**Comment by msahli2** [comment]
Add:
your ESP8266  must a static ip:ex 
WiFi.config(IPAddress(192,168,103,1), IPAddress(192, 168, 103,255), IPAddress(255, 255, 255, 0)) ;

**Comment by espiot328266** [comment]
> Add:
> your ESP8266 must a static ip:ex
> WiFi.config(IPAddress(192,168,103,1), IPAddress(192, 168, 103,255), IPAddress(255, 255, 255, 0)) ;

you can access to esp8266 by network that simple?
