### ISSUE TITLE
[Socket.io Websocket] Sends Disconnect message without stop and doesn't connect to the server!

### ISSUE THREAD

**Issue by WisterDesigns** [Links2004/arduinoWebSockets#132]
Hello everyone,
I'm using the WebSocketsClient.h library and I have some problems, The NodeMCU 12E doesn't connect to the Webserver don't know why.
**Arduino Code:**

``` cpp
/*
 * WebSocketClientSocketIO.ino
 *
 *  Created on: 06.06.2016
 *
 */

#include <Arduino.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <WebSocketsClient.h>

#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;


#define USE_SERIAL Serial

#define MESSAGE_INTERVAL 30000
#define HEARTBEAT_INTERVAL 25000

uint64_t messageTimestamp = 0;
uint64_t heartbeatTimestamp = 0;
bool isConnected = false;

void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {


    switch(type) {
        case WStype_DISCONNECTED:
            USE_SERIAL.printf("[WSc] Disconnected!\n");
            isConnected = false;
            break;
        case WStype_CONNECTED:
            {
                USE_SERIAL.printf("[WSc] Connected to url: %s\n",  payload);
                isConnected = true;

                // send message to server when Connected
                // socket.io upgrade confirmation message (required)
                webSocket.sendTXT("5");
            }
            break;
        case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);

            // send message to server
            // webSocket.sendTXT("message here");
            break;
        case WStype_BIN:
            USE_SERIAL.printf("[WSc] get binary lenght: %u\n", lenght);
            hexdump(payload, lenght);

            // send data to server
            // webSocket.sendBIN(payload, lenght);
            break;
    }

}

void setup() {
    // USE_SERIAL.begin(921600);
    USE_SERIAL.begin(115200);

    //Serial.setDebugOutput(true);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

      for(uint8_t t = 4; t > 0; t--) {
          USE_SERIAL.printf("[SETUP] BOOT WAIT %d...\n", t);
          USE_SERIAL.flush();
          delay(1000);
      }

    WiFiMulti.addAP("Linksys - HotBox", "123123");

    //WiFi.disconnect();
    while(WiFiMulti.run() != WL_CONNECTED) {
        delay(100);
    }

    webSocket.begin("192.168.1.105", 81);
    //webSocket.setAuthorization("user", "Password"); // HTTP Basic Authorization
    webSocket.onEvent(webSocketEvent);

}

void loop() {
    webSocket.loop();

    if(isConnected) {

        uint64_t now = millis();

        if(now - messageTimestamp > MESSAGE_INTERVAL) {
            messageTimestamp = now;
            // example socket.io message with type "messageType" and JSON payload
            webSocket.sendTXT("42[\"messageType\",{\"greeting\":\"hello\"}]");
        }
        if((now - heartbeatTimestamp) > HEARTBEAT_INTERVAL) {
            heartbeatTimestamp = now;
            // socket.io heartbeat message
            webSocket.sendTXT("2");
        }
    }
}
```

**Arduino Serial Monitor:**

```
[SETUP] BOOT WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 4
cnt 

connected with Linksys - HotBox, channel 11
dhcp client start...
[SETUP] BOOT WAIT 3...
[SETUP] BOOT WAIT 2...
[SETUP] BOOT WAIT 1...
ip:192.168.1.109,mask:255.255.255.0,gw:192.168.1.1
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
[WSc] Disconnected!
```

**Socket.io & Node.JS server Codes:**

``` js
var express = require('express');
app = express();
server = require('http').createServer(app);
io = require('socket.io').listen(server);

server.listen(81);
app.use(express.static('public'));

io.sockets.on('connection', function (socket) {

    console.log('Socket connected: ' + socket.conn.remoteAddress);

    socket.on('led', function (data) {
    });


    socket.on('disconnect', function(socket) {
        console.log('Socket disconnected');
    });
});


console.log("Server is running.");
```

Picture: http://prntscr.com/cxgvx0

Thanks for everyone's help!

**Comment by Links2004** [comment]
for socket.io change:
```cpp
 webSocket.begin("192.168.1.105", 81);
```
to

```cpp
 webSocket.beginSocketIO("192.168.1.105", 81);
```

**Comment by WisterDesigns** [comment]
Oh god, I'm trying for about seven days to fix this problem but nothing works and now it works!
What about the JAVA websocket server that is running on GlassFish server 4.1.1? It makes me the same problem so what I need to do in order to run it on GlassFish server 4.1.1 that runs on Java?

**Comment by Links2004** [comment]
can you capture the connection sequens to a GlassFish server?
may they require some header or cookie.

for testing its very useful to activate the debugging.
https://github.com/Links2004/arduinoWebSockets/issues/84#issuecomment-223647210

**Comment by WisterDesigns** [comment]
When I'm sending Data from the Server to the Client it shows me this:
```
[WSc] Connected to url: /socket.io/?EIO=3
[WSc] get text: 40
[WSc] get text: 42["Hello \n"]
[WSc] get text: 42["Hello \n"]
[WSc] get text:["Hello \n"]
```
**Node.JS code:**
```
socket.emit("Hello \n");
socket.emit("Hello \n");
socket.emit("Hello \n");
```
How to make it send me Just the Hello \n without all the other stuff and what this 40 and 42 stands for?
`[WSc] get text: Hello \n`

and how to make it stay connected all the time without any disconnection?

**Comment by Links2004** [comment]
the number are part up the socket.io IO protocol.
based on the complexity of messages you want to send, simple stripe them or Interpret them whats more reliable.

some references that help:
https://github.com/socketio/socket.io-protocol
https://github.com/socketio/socket.io-parser/blob/master/index.js


may @kiralikbeyin can help here, I only have code for Interpret the old socket.io 0.9 messages.

**Comment by WisterDesigns** [comment]
Is it hard to create a library like this? Where did you get all the knowledge needed to do it?

**Comment by Links2004** [comment]
I have learned almost all, my programming in a auto-didactic way, starting around my twelfth year.
at the beginning I looked at existing code modified it and learnt what it does and how it works.
since then (14 years later) I am a full time Developer and able to Programm in around ten languages, and on many different platforms.

the basic WS client and server code where working after ~3days, since then I improve the code and add new features when needed.
all the needed infos about the WS protocol were in the RFC6455,
from my point of view it where not really hard to do, since all info where there.
Only had to code it down In a efficient and easy to use way for a embedded device.

Unfortunately I can not say read this book or watch this tutorial, to get all info needed to writing a library like this, its more an progress or journey where you get at this point.
where you look at a your "project" with all the understanding and knowledge what you have build up.
some times its then only using all the known stuff, which can be some how boring,
some times you have a problem where you need weeks to get it working but when its working you are happy and satisfied that you get it working.
the best projects are where you can use you knowledge, but still learn something new, or a more effective way to get thinks done.

**Comment by WisterDesigns** [comment]
How old are you now days? I don't know how to save the string the Client gets from the Server. Do you have maybe an example or code that saves the text that the Client recieves as a string?

**Comment by Links2004** [comment]
I am 26.
what exactly you mean with save? need it survive a reboot, if not use a global variable to store the data.
```cpp
String last_data = "";
void webSocketEvent(WStype_t type, uint8_t * payload, size_t lenght) {

......

 case WStype_TEXT:
            USE_SERIAL.printf("[WSc] get text: %s\n", payload);
            last_data = payload;
            // send message to server
            // webSocket.sendTXT("message here");
            break;
.....
}
```

**Comment by Barman54** [comment]
Hi, 
I used yout library on 8266 with success but then I tried to make a websocketsserver on a mega. I get some errors because the esp lib has some more members as  the ethernet lib has. After commenting out these lines I got a websocketsclient which continuously says 'disconnected' (allthough no clients have been connected). 

To make this message not too long I attach the .ino file (as .txt). I started with the esp version and changed
- added debug.h because of 'hexdump'
- added Hash.h and the commented it out 
- commented out 'IPAddress ip = webSocket.remoteIP(num)' bev=cause I could not find a comparable member in WebSocketServer
- changed webSocket.begin(); to webSocket.beginSocketIO("192.168.0.38", 81); but the latter is no member of class WebSocket

Can you point me to the right direction?
[WebSocketServerAVR.txt](https://github.com/Links2004/arduinoWebSockets/files/547212/WebSocketServerAVR.txt)

**Comment by WisterDesigns** [comment]
You can't compare the payload to the last_data string variable, it shows an error:
```
exit status 1
invalid conversion from 'uint8_t* {aka unsigned char*}' to 'const char*' [-fpermissive]
```
how to make it work?

**Comment by Links2004** [comment]
@WisterDesigns 
```cpp
  last_data = (const char*)payload;
```

@Barman54 are you using the Mega version (1.4) or the ESP (2.0) version?

**Comment by Barman54** [comment]
Hi,
I use library 1.3.0 for the Mega.

**Comment by WisterDesigns** [comment]
The NodeMCU disconnects from the websocket after a short period of time and I don't have any idea what is the problem and how to fix it?
And where did you learn how to create all this libraries for the micro controller, where can I learn how to create them and where to start from?
Thanks!

**Comment by Barman54** [comment]
Hi,
I was away for some time.
I opened the Arduino interface but no 1.4.0. The doc says I should use 1.3.0, which I installed. Any suggestions how I can get websockets working using ethernet on a mega?
Thanks in advance for your reaction!

**Comment by Links2004** [comment]
@Barman54 

the socket.io code is not ported to AVR, its only on the ESP.
currently there is only a AVR client example.

https://github.com/Links2004/arduinoWebSockets/blob/master/examples/WebSocketClientAVR/WebSocketClientAVR.ino

the hexdump is not mandatory only used to print bin data in the sketch, the websocket itself does not need it.

using ```remoteIP``` is not possible for W5100 since there is no API to get a IP of the client by the socket.

currently have no Mega with a Ethernet shied to do some tests.
by looking at you code I see no error

version 1.4 has some bugfixs which shout still be compatible to AVR,
but I never tested it on AVR.
all after v2 is not compatible with AVR since AVR leaks the support for c++ namespaces.

**Comment by Links2004** [comment]
https://github.com/Links2004/arduinoWebSockets/issues/142
