### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by onkie** [Links2004/arduinoWebSockets#155]
(Sorry, English is not my language) 
Thanks for your library Websocket ;) 
After installing the latest websocket version:
- The ESP-WS-clients are not disconnected and not reconnected after a reset/restart of the ESP-WS-server. (reconnect only after PING, Send... or restart of the ESP-WS-Clients)
With the older versionI i had this problem not. 
- After a reset/restart of the ESP-WS-clients the ESP_WS-server adds the same IP to the list of connections.
```
// used from WebSocketsServer.h
#define WEBSOCKETS_SERVER_CLIENT_MAX (5) 
WSclient_t _clients[WEBSOCKETS_SERVER_CLIENT_MAX];
IPAddress remoteIP(uint8_t num);

// test code
for (uint8_t i=0; i<WEBSOCKETS_SERVER_CLIENT_MAX; i++) {
    if (webSocket.remoteIP(i) )
    Serial.println(webSocket.remoteIP(i)); 
}
```
1 start and 4 restarts/resets and _clients[] is full with one client. 

**_OUTPUT:_**
WS Clients:
192.168.1.17 **_(after start)_**
192.168.1.17 **_(after reset-1)_**
192.168.1.17 **_(after reset-2)_**
[3] type: 2, txt: /    **_ (3rd restart of the same ESP-WS-client)_**
[3] Connected from 192.168.1.17 url: 
[3] type: 3, txt: Connected
WS Clients:
192.168.1.17
192.168.1.17
192.168.1.17
192.168.1.17 **_(added after restart-3)_**

**Comment by Links2004** [comment]
the disconnect handling is done in the TCP stack of the ESP.
since there is no "keep Alive" Implementation, 
detecting a dead connection is only possible when data is send.
using ping is the best way to do this since it results in the smallest packages.
since not all TCP clients / servers out there support ping,
its not done automatically in the lib and its up to the user when he sends pings.
for a longtime stable connection its recommended to do ;)

**Comment by onkie** [comment]
Thanks for this rapid response ;)
To get it working again: Server PING/PONg and Client PING that was already implemented, with timers, in my code.
