### ISSUE TITLE
ESP8266 WS Server don't recognizing android client's disconnection

### ISSUE THREAD

**Issue by DeathSoldier** [Links2004/arduinoWebSockets#184]
I have create a Android App(WS Client) which I use Autobahn Library. In ESP8266(NodeMCU) I have the WebSocket Server with library arduinoWebSockets. My problem is when I am connected to the AP and then   close the Wifi and disconnect from access point in Android the ESP don't recognize the disconnect.

Why this can happen ? 

Thanks!

**Comment by Links2004** [comment]
the TCP close is not send from Android to ESP since WiFi is disconnected.
to detect this on ESP side you can use the "ping" feature of the lib.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L83
https://github.com/Links2004/arduinoWebSockets/issues/144#issuecomment-261706699

**Comment by DeathSoldier** [comment]
But how the disconnect  succeed when my Android app call the onDestroy function?

**Comment by Links2004** [comment]
at that point you still habe WiFi and the TCP disconnect can be send, 
If you kill the WiFi there is no way to send the TCP disconnect any more.

**Comment by DeathSoldier** [comment]
OK. I think the connection is lost when the ws connection is closed automatic.

**Comment by Links2004** [comment]
the why makes no difference, if a connection get lost for some reason,
the ESP can detect it when you use the ping function, simple call it for example all 30sec.
