### ISSUE TITLE
How to manage web sockets avoiding impact on other fast processes? - Question

### ISSUE THREAD

**Issue by gnkarn** [Links2004/arduinoWebSockets#215]
I have an led matrix with APA102 leds , managed by an ESP8266 .
it connects to a web client in order to receive data via web sockets , n order to change modes an other adjustments . ESP is SERVER  for this connection.
on the other hand , one of the modes is "video" where the matrix can receive live video from a camera through binary web sockets . ESP and the video sender are Clients , of a _Heroku Node server , which dos nothing, just receives packets on one hand and send them out on the other .

In this case , any animation that the matrix is doing is severely affected in performance ,  when the Websocket on message is being executed on the ESP side .

Is there something else i copped do in order to "decouple better " the on message call back, with the Leds update ?

it seams that all processing gets "trapped" in the on message , until the web socket frame is totally received ...

appreciate your advice ..
gus

**Comment by Links2004** [comment]
you can try the async mode, this will give you more CPU time.
since the sync variant block until the full frame is processed.
https://github.com/Links2004/arduinoWebSockets#esp-async-tcp

or trigger you matrix write out with a timer.

with my WS2812 strips I simple use the I2S bus with a buffer, which is working fine.
since the I2S write out is implemented in the ESP8266 chip with DMA it is not conflicting with the wifi communication.

**Comment by gnkarn** [comment]
Thankyou Markus,
will try async tomorrow, is there any way to send frames continuously to the ESP, without the need of reading them ( to automatically drop packets ) , or the only way to do that is by changing to Udp?
