### ISSUE TITLE
How to pass a binary data to an array ?

### ISSUE THREAD

**Issue by gnkarn** [Links2004/arduinoWebSockets#219]
Hi  Markus, 
im little by little  making progress on my debugging , but there is still a lot to do ,

in this case my question is about data organization in memory , on the binary received payload , and on  a generic array -

im passing the hex values received in the binary payload to the array ( that holds the R,G,B c_leds( x,y) values in serpentine pattern, by doing this

case WStype_BIN:
		//USE_SERIAL.printf("[WSc] get binary length: %u\n", length);
		//herokuWs.sendBIN(payload, length); //Do not enable for final production
		//hexdump(payload, length);//
		sendAck();
		**memcpy(&c_leds, payload, length * sizeof(uint8_t));**

but it seams , that the data is not organized , the same way it was originally sent,
am i missing an hex , uint8_t conversion also  ?

appreciate your advice .
gus

**Comment by Links2004** [comment]
the data is send the 100% the same as it is inputted. the websocket does not tamper with the data at all.
can you post you complete code?
with this alone its hard to see whats going wrong.

**Comment by gnkarn** [comment]
code is here
[https://github.com/gnkarn/Funky_Control8266-jqm/tree/Heroku%2Bp5js%2BESP/Funky_Control8266-jqm]

the communication functions are mainly in here
[https://github.com/gnkarn/Funky_Control8266-jqm/blob/Heroku%2Bp5js%2BESP/Funky_Control8266-jqm/LEDWebsockets.h](url)

**Comment by Links2004** [comment]
you use ```memcpy``` with the ```cLEDMatrix``` class pointer.
this will end up in a big memory mess.

since the code for the ```cLEDMatrix``` class is not include in the repo, i can not say whats the best way to deal with this.
but i can see to ways:

1. the class gives you access to the correct pointer for the LED data, and you server sends in the correct memory endianess and memory Alignement (then memcpy is a really fast and easy way).
2. you need to Interpreter the incoming binary data and call some sort of set function for each pixel.

**Comment by gnkarn** [comment]
yes understand what you mean , will look into it , from the hex dump , i  the  received data seams correct, will send a "test" pattern to detect where the errors are . thank you

**Comment by gnkarn** [comment]
i made it to work , thanks
