### ISSUE TITLE
Hash is missing.

### ISSUE THREAD

**Issue by tikagnus** [Links2004/arduinoWebSockets#226]
Hi Guys. 
I'm using platformion with CLion.
Your library is great, but I got this error when I try to build.
Could you help me ?
`Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/WebSockets.o
Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/WebSocketsServer.o
Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/libb64/cdecode.o
Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/libb64/cencode.o
lib/arduinoWebSockets/src/WebSockets.cpp:41:18: fatal error: Hash.h: No such file or directory
#include <Hash.h>
^
compilation terminated.
*** [.pioenvs/d1_mini/lib/arduinoWebSockets/WebSockets.o] Error 1
`

**Comment by Sparkxxx** [comment]
Hash.h: No such file or directory #include <Hash.h> download it in the library directory 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Bogdan TICA <notifications@github.com> Date: 8/17/17  23:10  (GMT+02:00) To: Links2004/arduinoWebSockets <arduinoWebSockets@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Links2004/arduinoWebSockets] Hash is missing. (#226) 
Hi Guys.

I'm using platformion with CLion.

Your library is great, but I got this error when I try to build.

Could you help me ?

Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/WebSockets.o Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/WebSocketsServer.o Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/libb64/cdecode.o Compiling .pioenvs/d1_mini/lib/arduinoWebSockets/libb64/cencode.o lib/arduinoWebSockets/src/WebSockets.cpp:41:18: fatal error: Hash.h: No such file or directory #include <Hash.h> ^ compilation terminated. *** [.pioenvs/d1_mini/lib/arduinoWebSockets/WebSockets.o] Error 1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Links2004/arduinoWebSockets","title":"Links2004/arduinoWebSockets","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Links2004/arduinoWebSockets"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Hash is missing. (#226)"}],"action":{"name":"View Issue","url":"https://github.com/Links2004/arduinoWebSockets/issues/226"}}}

**Comment by Links2004** [comment]
the `Hash.h` comes from the ESP8266 core.
https://github.com/esp8266/Arduino/blob/master/libraries/Hash/src/Hash.h
may your IDE does not include it automatically in your project.
