### ISSUE TITLE
Client is available

### ISSUE THREAD

**Issue by ing-IP** [Links2004/arduinoWebSockets#321]
Hi, I use nodeMcu like webserver and I should be able to run one part of my alghorithm only if there is client connected to the server. There are lot of examples where they use function 'webSocket.onEvent' and then you will get client is connected or disconnected but this method doesnt work in situation when client lost network connection(eg weak internet connection) with server (probably because client can not send any event), in this case program think that there is connected client
is there any possibility to check current status of Client without Event function?

**Comment by Links2004** [comment]
yes, 
you can use `sendPing` to check the connection to a client actively 

https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L85-L86

**Comment by Links2004** [comment]
the GPN18 branch has functions for that.

Server
https://github.com/Links2004/arduinoWebSockets/blob/gpn18/src/WebSocketsServer.h#L98

Client
https://github.com/Links2004/arduinoWebSockets/blob/gpn18/src/WebSocketsClient.h#L90

but keep in mind that this are the stats of the TCP stack, and the value may is wrong since the TCP stack does detect a disconnect only when data is send and the sending fails.
