### ISSUE TITLE
How temporary pause websocket server in the loop() to speed-up main functions

### ISSUE THREAD

**Issue by williamesp2015** [Links2004/arduinoWebSockets#325]
I have experienced considerable delay during saving data on a SD card and if I skip webSocket.loop(); when start key pressed, it can not connect to the client after resume webSocket.loop();

**Comment by Links2004** [comment]
if, you dont call the loop for to long there are two thinks that can happen:

- the client disconnect from itself since it not get a answer any more form the server
- the internal TCP buffer runs full and starts loosing data --> Connection gets lost.

best think to do is to disconnect the client manually and Programm it to auto Connect.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L91
