### ISSUE TITLE
Increase performance

### ISSUE THREAD

**Issue by Vitorbnc** [Links2004/arduinoWebSockets#45]
Hello again!
I've tested your WebSocketClient sketch and it's pretty fast. However, if I send many messages they pile up and take some time to be printed. Is there any way to make it faster?

**Comment by Links2004** [comment]
what do you mean with printed? 
messages from or the the ESP?

I working on async one, which can handle many small packages send out from the ESP better.
with the current one you can get around 900 messages per second.

**Comment by Vitorbnc** [comment]
I mean printed on the Serial Monitor of the Arduino IDE. I have a simple web page with some buttons. The buttons trigger events on my Node server through Socket.io. Then, the server sends messages to Arduino. through  WebSocket.

**Comment by Vitorbnc** [comment]
I have another version too, it's all the same, but Arduino communication is done using MQTT. When I send many messages (click the button quickly) they show a small delay, but don't pile up.

**Comment by Links2004** [comment]
the WebSocket dont change the way Serial works.
not sure what the problem is.
do you send the same amount of messages with the same timing in your tests?

I run my serial at 921600 and can print every message where I get from ws with ~900 messages per second, the sync network calls are the limit here. 

at some point the serial buffer is full and then the system waits until it can send out your serial data.
but this is a standard behavior of Serial / Arduino API.

**Comment by Vitorbnc** [comment]
Do you send the messages from Nodejs ws library too? I'm using Node as server and Arduino as client.

**Comment by Links2004** [comment]
yes plain nodejs + WebSockets for the test
js code:
https://github.com/Links2004/arduinoWebSockets/blob/master/tests/webSocketServer/index.js

**Comment by Vitorbnc** [comment]
I tried your example, but even at 921600 I get the same problem. I think it may be something with parsing. Anyway, thanks a lot for your help! ;) ;)

**Comment by Links2004** [comment]
async one for testing:
https://github.com/Links2004/arduinoWebSockets/tree/async
