### ISSUE TITLE
Infinite recursive loop

### ISSUE THREAD

**Issue by maksim-ka** [Links2004/arduinoWebSockets#466]
https://github.com/Links2004/arduinoWebSockets/blob/c038f100d68b8e5d0a96f25dd1609ff28592b02f/src/WebSocketsServer.cpp#L191
should be `return sendTXT(num, (uint8_t *)payload, length, true);`    

https://github.com/Links2004/arduinoWebSockets/blob/c038f100d68b8e5d0a96f25dd1609ff28592b02f/src/WebSocketsServer.cpp#L235
should be`return broadcastTXT((uint8_t *)payload, length, true); `

https://github.com/Links2004/arduinoWebSockets/blob/c038f100d68b8e5d0a96f25dd1609ff28592b02f/src/WebSocketsServer.cpp#L270
should be return sendBIN(num, (uint8_t *)payload, length, true);
 
https://github.com/Links2004/arduinoWebSockets/blob/c038f100d68b8e5d0a96f25dd1609ff28592b02f/src/WebSocketsServer.cpp#L298
should be `return broadcastBIN((uint8_t *)payload, length, true); `

If it's meant to be like that could someone please clarify that

**Comment by Links2004** [comment]
no the code is correct. 
The ```headerToPayload``` is only possible for datatypes that can modified and are binary.
and since the parameter is optional there is no need to add the parameter.
https://github.com/Links2004/arduinoWebSockets/blob/c038f100d68b8e5d0a96f25dd1609ff28592b02f/src/WebSocketsServer.h#L63

it comes down to that: 

```cpp
 return sendTXT(num, (uint8_t *)payload, length); 
```

is the same as

```cpp
 return sendTXT(num, (uint8_t *)payload, length, false); 
```
