### ISSUE TITLE
use of websockets within wifimesh

### ISSUE THREAD

**Issue by unknown1337** [Links2004/arduinoWebSockets#47]
Dear,

Your library seems really good, especially after reviewing some of the test results (messages/second) between two instances (pc and esp8266).

Do you think that your code running on 20/30 esp8266 (each node being both server and client, connected to all of the other nodes and connected to a router (for ntp e.g.)) is capable of handling 20/30 active ws connections on each of the nodes (and about 1 message per second per connection), without the use of wss, so normal wc over TCP?

Thank you so much in advance! 

ps, am I correct when I claim that an (extra) ws connection doesn't require much resources if no messages are being pushed over the channel (except from the ping/pong)?

**Comment by Links2004** [comment]
the ESP module can only handle 5 TCP connections one the same time (SDK limitation).
The ws server code itself can handle more its only a question of the WEBSOCKETS_SERVER_CLIENT_MAX define.
may us a raspberry pi as router then you can run a ws server there and all ESPs connect there.
but its no mesh any more then, but since you have a router in your setup the network will go down anyway if the router is offline.
