### ISSUE TITLE
WebSocketsServer closes active sockets when stat is disconnected (ESP8266WiFi)

### ISSUE THREAD

**Issue by Mitxel111** [Links2004/arduinoWebSockets#502]
The code is running in ESP8266 under Arduino ESP8266 library. 

ESP8266 is working in WiFi.mode(WIFI_AP_STA). ESP is connected to both the AP network and to (an independent) Stat network. There is a WebSocketsServer working through the AP network that has 2 or 3 connected active client sockets. All this is working flawlessly.

But when the code disconnects the Stat network (WiFi.disconnect()), in which there are no sockets, the WebSocketsServer closes all connected (AP network) sockets. 

Additionally, the server also closes all sockets connected through the AP network when:

- The code tries to connect, in Station mode, to an SSID not present (WL_NO_SSID_AVAIL)

- The code tries to connect, in Station mode, to a present SSID but using a bad pass-word (WL_CONNECT_FAILED)

**Comment by zhubinsheng** [comment]
Hello, I have a similar problem. Have you solved this problem? Thank you very much for your reply

**Comment by Mitxel111** [comment]
Unfortunately I have been unable to find a solution until now.

a greeting

**Comment by Links2004** [comment]
the problem is that the ESP is switching channels to find a new AP when the STA disconnects.
this results in a connection lost for the clients connected to the AP of the ESP.
and when the ESP finds the WiFi for STA again it may switches channels again --> AP clients connection gone again.

may this helps to understand it:
https://github.com/esp8266/Arduino/issues/119#issuecomment-157418957
