### ISSUE TITLE
Next version of espressif-esp32 will fail to compile

### ISSUE THREAD

**Issue by schlaegerz** [Links2004/arduinoWebSockets#525]
I'm trying out the newest espressif esp32 libraries and this library fails to compile

#include <hwcrypto/sha.h>
is being moved to
#include <esp32/sha.h>

I don't quite know what the solution should be, but just thought I would put this here so a decision can be made before this gets updated for most people.

**Comment by Links2004** [comment]
the travis job is building against https://github.com/espressif/arduino-esp32.git master, and has not shown any include problems, can you give more details?

**Comment by chemicstry** [comment]
There is `idf-release/v4.0` branch, which is based on esp-idf v4 and it has changed include path as indicated above. It will fail to compile once it is released in master. Unfortunately, I couldn't find a way to test for idf >= 4 version, because older idfs don't have version defines.

Platform.io already uses esp-idf v4 and compiling arduinoWebSockets fails
