### ISSUE TITLE
Is there any way to limit the queue?

### ISSUE THREAD

**Issue by whakru** [Links2004/arduinoWebSockets#534]
Is there any way to limit the queue?
If the ESP is not coping with the number of packets, then they go to a huge queue. may end up hanging.

**Comment by Links2004** [comment]
the websocket Protokoll is build in a way that requires to parse all TCP packets,
since you only know where the next message is when you have parsed the last one.
the only think you can skip easy is the user custom code in `webSocketEvent`.
and with some modifications to the lib the creation of the buffer for the payload creation for `webSocketEvent` but the WS header needs to be always parse, and all TCP packets need to be handled.
best think is to designe you protocol in a way that allows the ESP to inform the other side when its ready to handle the next X messages.
