### ISSUE TITLE
Voice data streaming issue

### ISSUE THREAD

**Issue by sskorol** [Links2004/arduinoWebSockets#560]
@Links2004 hi Markus,

Trying to figure out how binary data is sent, as a server cannot correctly interpret received payload.

I have a microphone array with esp32 on board. Here's a code snippet how the actual voice data is read and sent via sockets:

```cpp
    int16_t voicebuffer[VOICE_BUFFER_SIZE]; // VOICE_BUFFER_SIZE = 1024
    for (uint16_t i = 0; i < VOICE_BUFFER_SIZE; i++) {
        voicebuffer[i] = microphoneArray.Beam(i);
    }
    wsClient.sendBIN((uint8_t *) voicebuffer, VOICE_BUFFER_SIZE);
```
The voice recognition server accepts data in the following formats: https://github.com/alphacep/vosk-api/blob/master/src/kaldi_recognizer.cc#L217-L270

The output transcription seems damaged, as I'm getting some words' pieces (just a mess). It usually happens when the input data format doesn't match server's expectation. Note that the above code snippet perfectly works with MQTT client, which sends data the following way: https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.cpp#L448-L472

```cpp
mqttClient.publish(topic, (uint8_t *) voicebuffer, VOICE_BUFFER_SIZE);
```

Could you please advise if an additional data conversion is required? Or does this library even support such kind of tasks?

**Comment by Links2004** [comment]
Hi,

at a first look I say you send only half of your data.
your data buffer is ```int16_t```  * 1024 which results in 2048 byte but you only 1024 byte.
since you use VOICE_BUFFER_SIZE as size.
most likely you need `(VOICE_BUFFER_SIZE * sizeof(int16_t))`.

the lib does not transform or modify the data you send, so you can send any data you like in any format, 
but keep in mind that the size in the `sendBIN` are bytes.
and if data latency is critical you may want to limit you data to one TCP packed and not fragment it a 
good start for this is to limit it to less then 1400 byte (a detailed calculation can be found in some other issues).

not sure how the websocket is connected to the `AcceptWaveform` function, but make sure that the data endianness is matching (byte order in the int16_t).
and that you only pipe the websocket payload in and not the full TCP stream ;)

**Comment by sskorol** [comment]
@Links2004 You mean I need to convert int16_t array to uint8_t* first?

Regarding fragmentation: the server continuously sends intermediate transcription in response. And as it's a real-time voice-processing, I can't predict the overall data size to send it in a single packet.

In terms of `AcceptWaveform`, those code is used by different client libraries, e.g. https://github.com/alphacep/vosk-server/blob/master/websocket/asr_server.py#L42. So there's no additional processing on WS side. It just redirects the message to C-code.

**Comment by Links2004** [comment]
you not need to convert only cast (what you are doing already).
but you need to provide the correct size in bytes.

```cpp
 wsClient.sendBIN((uint8_t *) voicebuffer, (VOICE_BUFFER_SIZE * sizeof(int16_t)));
```
fragment is not a problem for the library and
the web socket protocol can handle data sizes way beyond hat you can fit in any Mikrocontroller RAM, so no limitation there.

I am not sure which AcceptWaveform function the python code is triggering since the AcceptWaveform call has no size, and the only one with out size / len is ```AcceptWaveform(Vector<BaseFloat> &wdata)``` but the python websocket code most likely does not return a `BaseFloat` for binary data.

if your mqtt python code is working may compare the data types you put in to the `AcceptWaveform` function there. 

if you use the same `int16_t` buffer in you mqtt ESP code you most likely sending only half of your data there too.

side note:
the ESP is little-endian, not sure what the AcceptWaveform / vosk expects

**Comment by sskorol** [comment]
Figured it out. Seems like there was a combination of issues:
- sample rate mismatch: socket server in docker image was configured to accept 8k rate by default, however, a client was sending 16k; noticed that only while local debugging;
- `headerToPayload` option damages the input audio stream: there's a loud noise on top of the real voice (probably I've just misused this option);
- any buffer size > `VOICE_BUFFER_SIZE` damages the input audio stream: I've tested it by saving the input stream to wav file; if I set e.g. `(VOICE_BUFFER_SIZE * sizeof(int16_t))` or `(VOICE_BUFFER_SIZE * 2)` there's just a noise in the output file; only a strict `VOICE_BUFFER_SIZE` works both for ws and mqtt.

Anyway, thanks for your time! Hope WS will work much more stable than MQTT (that just stuck after some period of time on esp32).
