### ISSUE TITLE
How to stream the data from the server to the client?

### ISSUE THREAD

**Issue by mqmarathon** [Links2004/arduinoWebSockets#561]
I am a student starting to learn Arduino and Websockets myself. So please bear with me if what I am saying doesn't make sense.
I was able to make the echo test work with arduinoWebSockets. Now I am trying to build a system where I use a lux-sensor, TSL2591, with ESP32 as a server to stream the lux value to any client who connects to the server. I believe I can call a WS event function inside the server so that I can send data to the client without their request. First of all, I would like to know if this functionality is called? The current code (please see below) does not do what I want. Could you help me out here on how to stream the short string format data to any connected clients? Thanks a lot!

```cpp
#include <WiFi.h>
#include <WebSocketsServer.h>
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include "Adafruit_TSL2591.h"

// Constants
const char* ssid = "mqmara";
const char* password = "mqmara25";

// Globals
WebSocketsServer webSocket = WebSocketsServer(80);

//TSL2591
Adafruit_TSL2591 tsl = Adafruit_TSL2591(2591); // pass in a number for the sensor identifier (for your use later)

// Called when receiving any WebSocket message
void onWebSocketEvent(uint8_t num,
                      WStype_t type,
                      uint8_t * payload,
                      size_t length) {

                        
  uint32_t lum = tsl.getFullLuminosity();
  uint16_t ir, full;
  ir = lum >> 16;
  full = lum & 0xFFFF;
  String luxVal = String(tsl.calculateLux(full, ir));
  webSocket.sendTXT(num, luxVal);
  
  // Figure out the type of WebSocket event
  switch(type) {

    // Client has disconnected
    case WStype_DISCONNECTED:
      Serial.printf("[%u] Disconnected!\n", num);
      break;

    // New client has connected
    case WStype_CONNECTED:
      {
        IPAddress ip = webSocket.remoteIP(num);
        Serial.printf("[%u] Connection from ", num);
        Serial.println(ip.toString());
      }
      break;

    // Echo text message back to client
    case WStype_TEXT:
      Serial.printf("[%u] Text: %s\n", num, payload);
      webSocket.sendTXT(num, payload);
      break;

    // For everything else: do nothing
    case WStype_BIN:
    case WStype_ERROR:
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
    default:
      break;
  }
}

void setup(void) 
{
  // Start Serial Port
  Serial.begin(115200);

  // Connect to access point
  Serial.println("Connecting");
  WiFi.begin(ssid, password);
  
  while ( WiFi.status() != WL_CONNECTED ) {
  delay(500);
  Serial.print(".");
  }

  // Print our IP address
  Serial.println("Connected!");
  Serial.print("My IP address: ");
  Serial.println(WiFi.localIP());

  // Start WebSocket server and assign callback
  webSocket.begin();
  webSocket.onEvent(onWebSocketEvent);
  
  displaySensorDetails();
  configureSensor();
}

void loop(void) 
{ 
  // Look for and handle WebSocket data
  webSocket.loop();
  
  delay(200);
}

void displaySensorDetails(void)
{
  sensor_t sensor;
  tsl.getSensor(&sensor);

  delay(500);
}

void configureSensor(void)
{
  tsl.setGain(TSL2591_GAIN_MED);
  tsl.setTiming(TSL2591_INTEGRATIONTIME_200MS);
}

void advancedRead(void)
{
  uint32_t lum = tsl.getFullLuminosity();
  uint16_t ir, full;
  ir = lum >> 16;
  full = lum & 0xFFFF;
  Serial.println(tsl.calculateLux(full, ir), 2);
}

void unifiedSensorAPIRead(void)
{
  /* Get a new sensor event */ 
  sensors_event_t event;
  tsl.getEvent(&event);
 
  /* Display the results (light is measured in lux) */
  Serial.print(F("[ ")); Serial.print(event.timestamp); Serial.print(F(" ms ] "));
  if ((event.light == 0) |
      (event.light > 4294966000.0) | 
      (event.light <-4294966000.0))
  {
    /* If event.light = 0 lux the sensor is probably saturated */
    /* and no reliable data could be generated! */
    /* if event.light is +/- 4294967040 there was a float over/underflow */
    Serial.println(F("Invalid data (adjust gain or timing)"));
  }
  else
  {
    Serial.print(event.light); Serial.println(F(" lux"));
  }
}
```

**Comment by Links2004** [comment]
Hi, 

what you are searching ist the function called `broadcastTXT` the function will send the data to all connected clients and can be called basically anywhere in you code (using in IRQ is not recommended).

so most likely you need something like this (code not tested)
```cpp
unsigned long previousMillis = 0;        // will store last time LUX was updated
const long interval = 200;           // interval at which to send LUX (milliseconds)

void loop(void) 
{ 
  // Look for and handle WebSocket data
  webSocket.loop();
  
//  delay(200); // do not delay the webSocket.loop call this will end up in Problems with more data

  unsigned long currentMillis = millis();
  // check for LUX update need
  if (currentMillis - previousMillis >= interval) {
    // save the last time we updated the LUX
    previousMillis = currentMillis;

    uint32_t lum = tsl.getFullLuminosity();
    uint16_t ir, full;
    ir = lum >> 16;
    full = lum & 0xFFFF;
    String luxVal = String(tsl.calculateLux(full, ir));
    webSocket.broadcastTXT(luxVal);
  }
}

```

**Comment by mqmarathon** [comment]
Thank you so much! It worked!! 

I have another question that is irrelevant to the original question. But I couldn't find any good resources online.
So I wanted to ask you this question below as you already know what the WS server does. 

My plan is to make a C# websocket client that connects to the ESP32 server to get the real-time lux data. (Just like the server continuously receiving the data and print it out without closing) I don't want to use Unity for this project, which is my goal for this project. So it would be, I believe..., Windows Forms Application, but I don't know where to begin. There are so many templates (.Net Core, .Net Framework, ASP.Net, etc) and not enough tutorials about WS client with C#. Do you have any experience building a client with C# and real-time data receiving from the server? Any examples you might have? Any advice or pointing out a material that you think would be helpful for me to dig in would be greatly appreciated! 

Thanks a lot!

**Comment by mqmarathon** [comment]
> Hi,
> 
> what you are searching ist the function called `broadcastTXT` the function will send the data to all connected clients and can be called basically anywhere in you code (using in IRQ is not recommended).
> 
> https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L69
> 
> so most likely you need something like this (code not tested)
> 
> ```c++
> unsigned long previousMillis = 0;        // will store last time LUX was updated
> const long interval = 200;           // interval at which to send LUX (milliseconds)
> 
> void loop(void) 
> { 
>   // Look for and handle WebSocket data
>   webSocket.loop();
>   
> //  delay(200); // do not delay the webSocket.loop call this will end up in Problems with more data
> 
>   unsigned long currentMillis = millis();
>   // check for LUX update need
>   if (currentMillis - previousMillis >= interval) {
>     // save the last time we updated the LUX
>     previousMillis = currentMillis;
> 
>     uint32_t lum = tsl.getFullLuminosity();
>     uint16_t ir, full;
>     ir = lum >> 16;
>     full = lum & 0xFFFF;
>     String luxVal = String(tsl.calculateLux(full, ir));
>     webSocket.broadcastTXT(luxVal);
>   }
> }
> ```

**Comment by mqmarathon** [comment]
> Hi,
> 
> what you are searching ist the function called `broadcastTXT` the function will send the data to all connected clients and can be called basically anywhere in you code (using in IRQ is not recommended).
> 
> https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsServer.h#L69
> 
> so most likely you need something like this (code not tested)
> 
> ```c++
> unsigned long previousMillis = 0;        // will store last time LUX was updated
> const long interval = 200;           // interval at which to send LUX (milliseconds)
> 
> void loop(void) 
> { 
>   // Look for and handle WebSocket data
>   webSocket.loop();
>   
> //  delay(200); // do not delay the webSocket.loop call this will end up in Problems with more data
> 
>   unsigned long currentMillis = millis();
>   // check for LUX update need
>   if (currentMillis - previousMillis >= interval) {
>     // save the last time we updated the LUX
>     previousMillis = currentMillis;
> 
>     uint32_t lum = tsl.getFullLuminosity();
>     uint16_t ir, full;
>     ir = lum >> 16;
>     full = lum & 0xFFFF;
>     String luxVal = String(tsl.calculateLux(full, ir));
>     webSocket.broadcastTXT(luxVal);
>   }
> }
> ```

Thank you so much! It worked!!

I have another question that is irrelevant to the original question. But I couldn't find any good resources online.
So I wanted to ask you this question below as you already know what the WS server does.

My plan is to make a C# websocket client that connects to the ESP32 server to get the real-time lux data. (Just like the server continuously receiving the data and print it out without closing) I don't want to use Unity for this project, which is my goal for this project. So it would be, I believe..., Windows Forms Application, but I don't know where to begin. There are so many templates (.Net Core, .Net Framework, ASP.Net, etc - Looks like I need to use ASP.NET Core Signal R so far...) and not enough tutorials about WS client with C#. Do you have any experience building a client with C# and real-time data receiving from the server? Any examples you might have? Any advice or pointing out a material that you think would be helpful for me to dig in would be greatly appreciated!

Thanks a lot!

**Comment by Links2004** [comment]
Hi,

last time I touched Windows development / C#  is a long time ago.

looks like windows .NET Extensions for C# have clientwebsocket support:
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netframework-4.8

https://csharpdoc.hotexamples.com/en/class/System.Net.WebSockets/ClientWebSocket#

https://www.rebex.net/websocket/features/websocket-client.aspx

what you try is sure possible, but I have no idea how to use the dotnet class.

**Comment by kanaguyashwanth** [comment]
Hi, I am having a similar problem too which is related to broadcasting, I am trying to make a webserver where it allows the users to connect and chat from a webpage locally without using internet and the modules are connected like a mesh network.
I am using multiple nodes, and each node has a specific IP address, when I enter the IP address in a browser, it will land on a chat page.

But, the problem that I am facing is that it is not broadcasting the message to all the other nodes and I tried to alter the code accordingly but I'm helpless. I don't know where I am going wrong. Please help me with this, thank you.

This is my code:
#include "painlessMesh.h"

#include <WiFi.h>
#include <ESPmDNS.h>
#include <WiFiClient.h>

#include "FS.h"   // Include the SPIFFS library
#include "SPIFFS.h"
#include <SPI.h> 
#include <ESPAsyncWebServer.h>
#include <WebSocketsServer.h>
#include <Wire.h>

#define MESH_PREFIX     "meshnet123"
#define MESH_PASSWORD   "password123"
#define MESH_PORT       5555

#ifndef STASSID
#define STASSID "ESP32_3"
#define STAPSK  "1234567890"
#endif
#define STATION_PORT     5555

const char* ssid = STASSID;
const char* password = STAPSK;
const int http_port = 80;
const int ws_port = 1337;


// TCP server at port 81 will respond to HTTP requests

// Globals
AsyncWebServer server(http_port);
WebSocketsServer webSocket = WebSocketsServer(ws_port);







/*--FUNCTIONS FOR PAINLESS MESH*/
painlessMesh  mesh;

// User stub
void sendMessage() ; // Prototype so PlatformIO doesn't complain

//String payload;
void sendMessage_from_Client(String payload) {  //pl
  //String msg = "Hello from node root";
  //msg += mesh.getNodeId();
  mesh.sendBroadcast( payload );                //pl
  //taskSendMessage.setInterval( random( TASK_SECOND * 1, TASK_SECOND * 5 ));
}

void receivedCallback( uint32_t from, String &msg ) {
  //Serial.printf("startHere: Received from %u msg=%s\n", from, msg.c_str());
  //create websocket event
  //webSocket.begin();//i adde this line
  webSocket.broadcastTXT(msg.c_str()); //when the message is receive broadcast to other users connected to it
}

void newConnectionCallback(uint32_t nodeId) {
    //Serial.printf("--> startHere: New Connection, nodeId = %u\n", nodeId);
}

void changedConnectionCallback() {
  //Serial.printf("Changed connections\n");
  //when the connection change, open the websocket
  // Start WebSocket server and assign callback
  //webSocket.begin();
 // webSocket.onEvent(onWebSocketEvent);
}

void nodeTimeAdjustedCallback(int32_t offset) {
    //Serial.printf("Adjusted time %u. Offset = %d\n", mesh.getNodeTime(),offset);

    //add this everytime the connection closed
    webSocket.loop();
}

/*END--FUNCTIONS FOR PAINLESS MESH*/





/*--FUNCTIONS FOR WEBSOCKET*/
// Callback: receiving any WebSocket message
void onWebSocketEvent(uint8_t client_num, WStype_t type, uint8_t * payload, /*pl*/ size_t length) {

  // Figure out the type of WebSocket event
  switch(type) {

     //Client has disconnected
    case WStype_DISCONNECTED:
      Serial.printf("[%u] Disconnected!\n", client_num);          
      break;

    // New client has connected
    case WStype_CONNECTED:
      {
        IPAddress ip = webSocket.remoteIP(client_num);
        Serial.printf("[%u] Connection from ", client_num);
        //Serial.println(ip.toString());
      }
      break;

    // Handle text messages from client
    case WStype_TEXT:

      // Print out raw message
      Serial.printf("[%u] Received text: %s\n", client_num, payload);   //pl

      //SEND THIS DATA
      // send data to all connected clients in a specific IP
      webSocket.broadcastTXT(payload, length);   //pl
      
      //send to other nodes server connected in the mesh network   
      sendMessage_from_Client((char*)payload);  //pl
      
      break;

    // For everything else: do nothing
    case WStype_BIN:
    case WStype_ERROR:
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
    default:
      break;
  }
}



// Callback: send homepage
void onIndexRequest(AsyncWebServerRequest *request) {
  IPAddress remote_ip = request->client()->remoteIP();
  //Serial.println("[" + remote_ip.toString() +
                 // "] HTTP GET request of " + request->url());
  request->send(SPIFFS, "/index.html", "text/html");
}

// Callback: send style sheet
void onCSSRequest(AsyncWebServerRequest *request) {
  IPAddress remote_ip = request->client()->remoteIP();
  Serial.println("[" + remote_ip.toString() +
                  "] HTTP GET request of " + request->url());
  request->send(SPIFFS, "/style.css", "text/css");
}

// Callback: send 404 if requested file does not exist
void onPageNotFound(AsyncWebServerRequest *request) {
  IPAddress remote_ip = request->client()->remoteIP();
  //Serial.println("[" + remote_ip.toString() +
                 // "] HTTP GET request of " + request->url());
  request->send(404, "text/plain", "Not found");
}

/*END EHERE--FUNCTIONS FOR WEBSOCKET*/




/*START OF THE MAIN PROGRAM*/
void setup(void) {
  
  Serial.begin(115200);


//InitializeSPIFFS();
  // Make sure we can read the file system
  if( !SPIFFS.begin()){
  //Serial.println("Error mounting SPIFFS");
    while(1);
  }
   SPI.begin();

  
//InitializeMesh();
//mesh.setDebugMsgTypes( ERROR | MESH_STATUS | CONNECTION | SYNC | COMMUNICATION | GENERAL | MSG_TYPES | REMOTE ); // all types on
  mesh.setDebugMsgTypes( ERROR | STARTUP );  // set before init() so that you can see startup messages

  mesh.init( MESH_PREFIX, MESH_PASSWORD, MESH_PORT );
  mesh.onReceive(&receivedCallback);
  mesh.onNewConnection(&newConnectionCallback);
  mesh.onChangedConnections(&changedConnectionCallback);
  mesh.onNodeTimeAdjusted(&nodeTimeAdjustedCallback);


//InitializeWIFI();
  // Connect to Wi-Fi network with SSID and password
  //Serial.print("Setting AP (Access Point)…");
  // Remove the password parameter, if you want the AP (Access Point) to be open
  WiFi.softAP(ssid, password);
  IPAddress IP = WiFi.softAPIP();
  //Serial.print("AP IP address: ");
  Serial.println("IP address: ");
  Serial.print(IP);
  Serial.println("");
  Serial.println("");
  Serial.println("Connect to ");
  Serial.print(ssid);
  //display.println(WiFi.localIP());
  //display.display(); 

//connectToServer();
  // On HTTP request for root, provide index.html file
  server.on("/", HTTP_GET, onIndexRequest);
  // On HTTP request for style sheet, provide style.css
  server.on("/style.css", HTTP_GET, onCSSRequest);
  // Handle requests for pages that do not exist
  server.onNotFound(onPageNotFound);
  // Start web server
  server.begin();


//connectToWebsocket();
  // Start WebSocket server and assign callback
  webSocket.begin();
  webSocket.onEvent(onWebSocketEvent);


//initializeMDNS();
  // Set up mDNS responder:
  // - first argument is the domain name, in this example
  //   the fully-qualified domain name is "esp8266.local"
  // - second argument is the IP address to advertise
  //   we send our IP address on the WiFi network
  if (!MDNS.begin("esp32")) {
    //Serial.println("Error setting up MDNS responder!");
    while (1) {
      delay(1000);
    }
  }
  //Serial.println("mDNS responder started");
  // Start TCP (HTTP) server
  //Serial.println("TCP server started");
  // Add service to MDNS-SD
  MDNS.addService("http", "tcp", http_port);

}




void loop(void) {
  mesh.update();
  webSocket.loop();
  //webSocket.broadcastTXT(payload);

}
