### ISSUE TITLE
Arduino Working with enc28j60 doc? [Question]

### ISSUE THREAD

**Issue by naiteon** [Links2004/arduinoWebSockets#614]
Hey guys is there any documentation or example on how to work with enc28j60?

I ask that because Ethernet.h doesn't work well with Arduino Mega, instead we had to use the EtherCard library.
First thing I've noticed reading thru the documentation here is that it is supposed to support enc28j60. But in the example I've noticed the Ethernet.h included. So my question is, has this been tested and is there any documentation on how to use this library with enc28j60 and Arduino Mega 2560?

Thanks!

**Comment by Links2004** [comment]
yes, enc28j60 and NETWORK_W5100 where tested, 
but the last test is a long time ago, since I not used a Mega 2560 in any network project since a long time.

to use the enc28j60 change the `WEBSOCKETS_NETWORK_TYPE` define to `NETWORK_ENC28J60`
https://github.com/Links2004/arduinoWebSockets/blob/11273d9f69159d22fc04f4f05b589248dda9f916/src/WebSockets.h#L56

keep in mind the the ATmega branch need to be used.

**Comment by naiteon** [comment]
@Links2004  Awesome man thank you so much! I'm gonna give it a try!
