### ISSUE TITLE
What is the difference between WebSocketsClient and SocketIOclient ?

### ISSUE THREAD

**Issue by kamleshkumarverma1986** [Links2004/arduinoWebSockets#671]
Hi...
First of all, Thanks for the great library.
Sorry for the stupid questions. I am completely new to this, just started learning 3 days back.

 I have basically one NodeJS server where my socket-io is running, and I want to connect that with my ESP8266 board.
I am able to connect my board with the SocketIOclient. but when I tried with WebSocketsClient, my connection is getting disconnect as soon as it connects.

So i just want to understand what is the main difference between WebSocketsClient and SocketIOclient?

**Comment by Links2004** [comment]
WebSocketsClient is for a plain websocket.
the SocketIOclient is for the socket.io Protokoll which is a websocket with engine.io and on top the socket.io

since you are having a NodeJS socket.io server you will need a SocketIOclient.

based on the socket.io server version you may need to set the engine.io version to 4.
```cpp
socketIO.begin("10.11.100.100", 80, "/socket.io/?EIO=4");
```

**Comment by kamleshkumarverma1986** [comment]
@Links2004 Thanks for the clarification, regarding the engine.io version to 4, that I know. even I am able to connect with my server with the EIO=4.

Only I had confusion about WebSocketsClient and SocketIOclient usage. Now I understand. Really thanks for the clarification.
