### ISSUE TITLE
Want to use a precompiled version for faster builds

### ISSUE THREAD

**Issue by shrynshjn** [Links2004/arduinoWebSockets#821]
Hi, 
I have a script that uses arduino-cli to generate a compiled build of my sketch that has a dependency on arduinoWebSockets among other libraries.
Each build takes a lot of time, as it compiles all the library in the sketch every time I build the sketch, the sketch has a unique identifier that changes for each build, is there some way I can speed up the builds? I get that using precompiled versions of libraries is one way to go, but I am not sure how to get them or use them. Any help would be much appreciated as right now it takes about a minute or more to compiled my code

**Comment by Links2004** [comment]
to my knowledge ther is no way to do this with the arduino CLI.

may take a look at platformio, since it is way more powerfull and allows you to use a real IDE with your code.
https://docs.platformio.org/en/stable/core/quickstart.html

I use platformio with vscode as IDE and its working very good.
building my projects direct via platformio CLI is possible to.

**Comment by shrynshjn** [comment]
Alright.

Thanks for the help @Links2004
