### ISSUE TITLE
Compatible with ESP-IDF？

### ISSUE THREAD

**Issue by ffalsk** [Links2004/arduinoWebSockets#899]

**Comment by Links2004** [comment]
the lib is not designed for the ESP-IDF directlly, it only works with the arduino layer on top.
and implementing this is not a easy tasks since this lib relasy on a log of arduino basics like `String`, the Network API and so on.

for ESP-IDF support it makes more sense to reimplement with lwIP style API in mind and go with c++ native functions only, but this is not planed for this lib.
