### ISSUE TITLE
Private message

### ISSUE THREAD

**Issue by kiralikbeyin** [Links2004/arduinoWebSockets#91]
How can i make a private connection like socket.io namespace/room ?

ESP8266 is client and a server on the internet..

**Comment by Links2004** [comment]
socket.io is a protocol on top of websockets. 
what exactly do you mean with private connection ?
you can us a SSL encryption when the ESP is the client for more privacy.

a room/namespace in socket.io only limits where the server sends his messages.
the same can be done with websockets only, its a question of what you implement on the server side.

**Comment by kiralikbeyin** [comment]
Hi Marcus

I understand now this is a server side config.

I couldnt make it work with socket.io Server with example of arduinoWebSockets
client.

Note that Serial is making trouble in client example.

Do you have any repo suggestion for node server?


6 Haziran 2016 Pazartesi tarihinde, Markus <notifications@github.com> yazdı:

**Comment by Links2004** [comment]
a basic nodejs server for ws can be found here:
https://github.com/Links2004/arduinoWebSockets/blob/master/tests/webSocketServer/index.js

I have local some code to connect to a Socket.io server but only for version 0.9 of the Socket.io protocol.
since 1.0 they change the protocol a bit and i never adapted since all is working fine with my ESPs.
If you interested i can uploade it.

**Comment by kiralikbeyin** [comment]
It will be nice to see socket.io example. Thank you.

**Comment by Links2004** [comment]
https://gist.github.com/Links2004/25966845ed38278bb4a2f4a44b5a30fb
