### ISSUE TITLE
string optimization for heap memory

### ISSUE THREAD

**Issue by jjssoftware** [Links2004/arduinoWebSockets#99]
Hi Markus I thought I'd table the idea of improving the situation with all of the hardcoded strings we have in this library. I've implemented something along these lines in my own code and I described that setup here: http://www.esp8266.com/viewtopic.php?f=32&t=10182

This pattern is a combination of preprocessor directives, PROGMEM and the implementation of a function to retrieve a given string by an enum value and it's worked well for me to reduce the volume of heap memory used by string literals. I'm wondering if you think this could work here too.

It does seem like it would be a good idea if we could at least wrap all of the DEBUG_WEBSOCKETS calls in some way because at the moment we have a situation where the strings involved here are using heap even if debugging has not been switched on.

To be honest at this stage I'm not sure how much we could save but just a quick browse shows there are a lot of strings - let's take a wild guess and say we could save 1Kb of heap  =)

**Comment by Links2004** [comment]
the ```DEBUG_WEBSOCKETS``` define are the same as nothing.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30-L35
so the debug strings will not end up in the heap when you not debug.

the most ```const char``` usage is in the http header exchange, and there its normally in combination with the string class.
simple warping with ```F()``` will do it here.
changing  ```const char``` used for the header exchange will not make problems,
but for all stuff that is used for WS messages its better to keep in heap since reading from flash has a performance impact.

**Comment by jjssoftware** [comment]
Thanks for your reply, I stand corrected. Debug related strings are not using heap memory when debugging is not enabled.
